# Dark
foreground            #604A52
background            #FCFBF9

# red (nord11)
color1  #8F5652

# green (nord14)
color2  #747B43

# yellow (nord13)
color3  #a3a389

# blue (nord9)
color4  #556995

# magenta (nord15)
color5  #83577D

# cyan (nord8)
color6  #477A7B

# white (nord5)
color7  #e5dfd3
